logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(%-5level) %clr(${spring.application.name}){blue} %clr(%msg){%-5level} %n"
  level:
    web: error
    '[io.github.danilotomassoni.core_hub.discovery]': info
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: true

management:
  info:
    os:
      enabled: true
    java:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "info, health" 
